spring.application.name=LibreChat-Contacts-Demo

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/contacts_db
spring.datasource.username=postgres
spring.datasource.password=Admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Batch
spring.jpa.properties.hibernate.jdbc.batch_size=300
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Static files
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Logging
logging.level.com.serri=INFO
# llm.api.key=${LLM_API_KEY:your-llm-key-here}
# gemini.api.key=${GEMINI_API_KEY:your-gemini-key-here}
gemini.api.key=AIzaSyD78GqsNF_ByOQEvyhtxtzDgnWXSr4UEw4
llm.api.key=AQ.Ab8RN6LBkDi5ncWE6U0wpNqgvHmdnMgTACFh5UbU3qdF0iHPOw
# Server
server.address=0.0.0.0
server.port=8080